### ISSUE TITLE
Disposed Microbe in Colony

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2582]
**Describe the bug**

Disposed Microbes are sometimes in Colony (or I say some Colony members are disposed not removing out of colony), causing the game to crash,

**To Reproduce**

Not easy to reproduce, but I've successfully reproduced many times using [Colony Crash.zip](https://github.com/Revolutionary-Games/Thrive/files/7148832/Colony.Crash.zip)

Earlier investigations at: [Community Forum](https://community.revolutionarygamesstudio.com/t/colony-binding-crash/3863)

The strange thing is that I can't break at Dispose() or QueueFree() so I can't figure out when it is disposed.

**Comment by hhyyrylainen** [comment]
It should be easier to find the places where game objects are Freed QueueFreed or the DetachAndQueueFree methods. Unless we are dealing with a serious Godot bug, all of the disposing happens because we removed an object from the tree. I've started on the microbe callbacks for when they are to be removed from the tree, but this sounds like not all places react / respect that.

**Comment by 84634E1A607A** [comment]
Solved in #3100, but its cause is still not found.

**Comment by hhyyrylainen** [comment]
I'm pretty sure I didn't switch the colony bind code to use the code to skip the disposed on the *current* object that I added in that PR. Also I think the colony bind actually runs into a disposed exception on the *other* object which my PR you linked didn't try to address at all.

**Comment by 84634E1A607A** [comment]
It does catch disposed problems, and I'm never able to crash the game again.

https://pastebin.com/5pyvZXQY

**Comment by hhyyrylainen** [comment]
That literally **did not** change the code that catches disposed exceptions from invokes.

I've actually in a separate PR added extra dispose checks in the colony forming: https://github.com/Revolutionary-Games/Thrive/pull/3099/files

**Comment by 84634E1A607A** [comment]
Okay... Found that.

**Comment by 84634E1A607A** [comment]
Unfortunately, 

```C#
ERROR: Index p_shape_index = 25 is out of bounds (total_subshapes = 0).
   at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 25 is out of bounds (total_subshapes = 0).
   at: shape_find_owner (scene/3d/collision_object.cpp:529)
Touched microbe has been disposed before engulfing could start
Touched microbe has been disposed before engulfing could start

Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microbe'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x0001b] in /root/godot/module
s/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:43
  at Godot.PhysicsBody.RemoveCollisionExceptionWith (Godot.Node body) [0x00001]
in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Ph
ysicsBody.cs:53
  at Microbe.OnColonyMemberRemoved (Microbe microbe) [0x0007e] in E:\source\repo
s\Thrive\src\microbe_stage\Microbe.Contact.cs:648
  at MicrobeColony.RemoveFromColony (Microbe microbe) [0x00083] in E:\source\rep
os\Thrive\src\microbe_stage\MicrobeColony.cs:81
  at Microbe.OnDestroyed () [0x00014] in E:\source\repos\Thrive\src\microbe_stag
e\Microbe.Contact.cs:601
  at Microbe.Kill () [0x0003f] in E:\source\repos\Thrive\src\microbe_stage\Micro
be.Contact.cs:418
  at Microbe.Damage (System.Single amount, System.String source) [0x001fc] in E:
\source\repos\Thrive\src\microbe_stage\Microbe.Contact.cs:339
  at Microbe.OnContactBegin (System.Int32 bodyID, Godot.Node body, System.Int32
bodyShape, System.Int32 localShape) [0x000d6] in E:\source\repos\Thrive\src\micr
obe_stage\Microbe.Contact.cs:1123

Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microbe'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x0001b] in /root/godot/module
s/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:43
  at Godot.PhysicsBody.RemoveCollisionExceptionWith (Godot.Node body) [0x00001]
in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Ph
ysicsBody.cs:53
  at Microbe.OnColonyMemberRemoved (Microbe microbe) [0x0007e] in E:\source\repo
s\Thrive\src\microbe_stage\Microbe.Contact.cs:648
  at MicrobeColony.RemoveFromColony (Microbe microbe) [0x00083] in E:\source\rep
os\Thrive\src\microbe_stage\MicrobeColony.cs:81
  at Microbe.OnDestroyed () [0x00014] in E:\source\repos\Thrive\src\microbe_stag
e\Microbe.Contact.cs:601
  at Microbe.Kill () [0x0003f] in E:\source\repos\Thrive\src\microbe_stage\Micro
be.Contact.cs:418
  at Microbe.Damage (System.Single amount, System.String source) [0x001fc] in E:
\source\repos\Thrive\src\microbe_stage\Microbe.Contact.cs:339
  at Microbe.OnContactBegin (System.Int32 bodyID, Godot.Node body, System.Int32
bodyShape, System.Int32 localShape) [0x000d6] in E:\source\repos\Thrive\src\micr
obe_stage\Microbe.Contact.cs:1123
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at Mono.Debugger.Soft.TcpConnection.TransportReceive(Byte[] buf, Int32 buf_offset, Int32 len)
   at Mono.Debugger.Soft.Connection.Receive(Byte[] buf, Int32 buf_offset, Int32 len)
   at Mono.Debugger.Soft.Connection.ReadPacket()
   at Mono.Debugger.Soft.Connection.ReceivePacket()
   at Mono.Debugger.Soft.Connection.receiver_thread_main()
Process ""D:/Program Files/Godot_v3.4.3-stable_mono_win64/Godot_v3.4.3-stable_mono_win64.exe" --path "E:/source/repos/Thrive" -v" terminated with exit code 1.

```

**Comment by hhyyrylainen** [comment]
That's unfortunate, so there is still some way to end up with disposed microbes in a colony? We should probably for now add a error print there and catch the disposed exception...

Also it seems you are using a Godot version we've never used for thrive `Godot_v3.4.3`, you should update to 3.4.4.

**Comment by 84634E1A607A** [comment]
I'll report this:

```C#
Microbe that should be bound to is disposed. This should never happen. Please re
port this. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microbe'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x0001b] in /root/godot/module
s/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:43
  at Godot.Spatial.GetGlobalTransform () [0x00001] in /root/godot/modules/mono/g
lue/GodotSharp/GodotSharp/Generated/GodotObjects/Spatial.cs:322
  at Godot.Spatial.get_GlobalTransform () [0x00001] in /root/godot/modules/mono/
glue/GodotSharp/GodotSharp/Generated/GodotObjects/Spatial.cs:50
  at Microbe.BeginBind () [0x000ac] in E:\source\repos\Thrive\src\microbe_stage\
Microbe.Contact.cs:1247
```

**Comment by 84634E1A607A** [comment]
Dead cells can be bound into a colony:

https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/Microbe.Contact.cs#L1191

Should be:

```C#
return !other.IsPlayerMicrobe && other.Colony == null && other.Species == Species && !other.Dead;
```
