### ISSUE TITLE
Investigate making the pause menu into a singleton and not separate component each stage has

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4805]
this will reduce the amount of times the thriveopedia page tree needs to be generated, so eventually we might need to switch to this approach to reduce the lag on opening the pause menu. As an added bonus the thriveopedia link click handler can be merged into the singleton.

**Comment by hhyyrylainen** [comment]
This would presumably also help with https://github.com/Revolutionary-Games/Thrive/issues/5075 as we would do less scene loading.

And example problematic callstack that this change would help with:

```
ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at ThriveopediaPatchMapPage.UpdatePlayerPatch(Patch patch) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 91
   at ThriveopediaPatchMapPage.SetGameForMap() in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 112
   at ThriveopediaPatchMapPage.UpdateCurrentWorldDetails() in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 61
   at Thriveopedia.set_CurrentGame(GameProperties value) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/Thriveopedia.cs:line 138
   at PauseMenu.set_GameProperties(GameProperties value) in /home/hhyyrylainen/Projects/Thrive/src/general/PauseMenu.cs:line 94
   at StageBase.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/StageBase.cs:line 307
   at CreatureStageBase`2.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/CreatureStageBase.cs:line 300
   at MicrobeStage.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/MicrobeStage.cs:line 1087
   at MicrobeStage._Ready() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/MicrobeStage.cs:line 197
```
