### ISSUE TITLE
Editor screen fails to load anything randomly (or any scene fails to load randomly)

### ISSUE THREAD

**Issue by Teashrock** [Revolutionary-Games/Thrive#5075]
### Describe the bug

I was playing as usual, clicked the reproduce button, but the editor screen has loaded without anything.

### To Reproduce

1. Open Thrive.
2. Load a save.
3. Play until reproduction, click the Editor button.
4. See the bug.

### Expected behaviour

Editor loading and allowing me to view all the data and edit my cell.

### Screenshots

![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/9ebc6400-8a7b-4ad6-8696-570e2a9aeaf2)
![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/9300317e-53cd-46b2-b11b-a870209a42ed)
![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/527f458c-2420-4993-a66e-fdb71e04113a)

### System information

- OS: Windows 11
- Graphics card: Radeon Vega 8 embedded in AMD Ryzen 5 3450U
- Thrive: 0.6.6

### Game Logs

https://pastebin.com/xn7NEX4X (there's only a chunk of `log.txt` due to the original file being too large)

**Comment by hhyyrylainen** [comment]
Here's the relevant error:
```
USER ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:334)
USER ERROR: Cannot connect to '': the provided callable is null.
   at: connect (core/object/object.cpp:1315)
USER ERROR: Index c.from &FLAG_MASK = 110 is out of bounds (nc = 17).
   at: instantiate (scene/resources/packed_scene.cpp:522)
USER ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Thriveopedia.AddPage(String name, IThriveopediaPage page) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/Thriveopedia.cs:line 332
   at Thriveopedia.set_CurrentGame(GameProperties value) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/Thriveopedia.cs:line 130
   at EditorBase`2.InitEditor(Boolean fresh) in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 550
   at MicrobeEditor.InitEditor(Boolean fresh) in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/editor/MicrobeEditor.cs:line 140
   at EditorBase`2.OnEnterEditor() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 668
   at MicrobeEditor.OnEnterEditor() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/editor/MicrobeEditor.cs:line 188
   at EditorBase`2._Ready() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 208
   at MicrobeEditor._Ready() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/editor/MicrobeEditor.cs:line 70
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at EditorBase`2.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/EditorBase(Of TAction, TStage)_ScriptMethods.generated.cs:line 458
   at MicrobeEditor.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/MicrobeEditor_ScriptMethods.generated.cs:line 228
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret)
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
USER ERROR: System.InvalidOperationException: Editor component not initialized
   at EditorComponentWithActionsBase`2.UpdateMutationPointsBar(Boolean tween) in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorComponentWithActionsBase.cs:line 78
   at EditorBase`2.OnMutationPointsChanged() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 833
   at EditorBase`2.CalculateMutationPointsLeft() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 928
   at EditorBase`2._Process(Double delta) in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/EditorBase.cs:line 281
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at EditorBase`2.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/EditorBase(Of TAction, TStage)_ScriptMethods.generated.cs:line 458
   at MicrobeEditor.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/MicrobeEditor_ScriptMethods.generated.cs:line 228
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret)
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
```

That last part then repeats indefinitely as the editor load has failed, which causes a ton of code to be skipped and it is an inconsistent state so it cannot work.

Here's my initial thoughts after looking at the code: this seems like a Godot scene instancing failure. The failing code is calling `AddPage("PatchMap");` in the Thriveopedia and it crashes on line `if (page.ParentPageName != null && allPages.Keys --` which should only be possible if the page variable is null. And the only reason that would be null if the scene instantiation fails, which Godot does seem to give some error message parts:
```
USER ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:334)
USER ERROR: Cannot connect to '': the provided callable is null.
   at: connect (core/object/object.cpp:1315)
USER ERROR: Index c.from &FLAG_MASK = 110 is out of bounds (nc = 17).
   at: instantiate (scene/resources/packed_scene.cpp:522)
```

My initial conclusion is that this also seems like a random Godot scene loading failure where it just randomly decides to not load a scene file correctly that usually loads completely fine. I haven't yet looked if there is an existing issue in Godot repository about this.

**Comment by Teashrock** [comment]
@hhyyrylainen 
Should I attach my current save file?

**Comment by Teashrock** [comment]
Nope. This time everything was good. Seems like a random Godot crash. They should debug the engine well.

**Comment by hhyyrylainen** [comment]
This is likely caused by: https://github.com/Revolutionary-Games/Thrive/issues/5209

**Comment by hhyyrylainen** [comment]
I've opened a new issue to Godot: https://github.com/godotengine/godot/issues/109798

**Comment by Teashrock** [comment]
@hhyyrylainen 
Okay, I hope they'll fix this soon.

**Comment by hhyyrylainen** [comment]
Just to make sure this is documented, sometimes the error looks like this when loading a scene:

```
ERROR: Cannot get class ''.
ERROR:    at: _instantiate_internal (core/object/class_db.cpp:546)
ERROR:    C# backtrace (most recent call first):
```

**Comment by hhyyrylainen** [comment]
There might be some indication that this issue is no longer as prevalent as before so we should keep an eye out after 1.0 tomorrow to see if we again get game scene load failures reported or not.

**Comment by hhyyrylainen** [comment]
There are still scene loading issues: https://www.reddit.com/r/thrive/comments/1pp579x/cannot_open_editor_in_1000_only_happened_late/

**Comment by RyuDanuer** [comment]
We should remove it from the milestone, we have noticed we cannot fix this.

**Comment by hhyyrylainen** [comment]
This is the *most* reported Thrive bug, with many weeks getting multiple reports of this general problem of the engine blowing up. As a result I will not be removing it from the milestones as it is the most important bug and has been for over a year now. And will continue to be until it is fixed (hopefully by an updated engine version at some point but none of my reported issues to the Godot engine repo done by me have been fixed).

**Comment by gunohaozheum** [comment]
Also hit this on Windows: the process died with exit code -1073741819 (access violation) right after `Parameter "tex" is null` while loading a save (Steam 1.6.0.0, Windows 11 25H2, NVIDIA RTX 5060 Laptop GPU, Vulkan Forward+). Full report and log: https://github.com/Revolutionary-Games/Thrive/issues/6981#issuecomment-5716378641
