### ISSUE TITLE
Godot scene loading with NodePaths seemingly fails randomly after some time

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5209]
It seems like NodePaths get sometimes loaded as null into C# classes seemingly randomly. The same scenes load correctly hundreds of times.

This has been reported to Godot: https://github.com/godotengine/godot/issues/93083 

This likely causes:
- https://github.com/Revolutionary-Games/Thrive/issues/5075
- https://github.com/Revolutionary-Games/Thrive/issues/5070

A potential workaround is to switch to:
- https://github.com/Revolutionary-Games/Thrive/issues/4940

**Comment by hhyyrylainen** [comment]
Another case:
```
Starting load of save: auto_save_4.thrivesave
World generation settings: [LAWK: True, Difficulty: hard preset, Life origin: Vent, Seed: 7618708444814157935, Day/night cycle enabled: True, Day length: 180, Include multicellular: True, Easter eggs: True]
USER ERROR: Node not found: "HSplitContainer/PatchDetailsPanel" (relative to "/root/MicrobeStage/PauseMenu/Thriveopedia/MarginContainer/VBoxContainer/HBoxContainer3/MarginContainer/ThriveopediaPatchMapPage").
   at: get_node (scene/main/node.cpp:1651)
USER ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at ThriveopediaPatchMapPage.UpdatePlayerPatch(Patch patch) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 114
   at ThriveopediaPatchMapPage.SetGameForMap() in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 135
   at ThriveopediaPatchMapPage.UpdateCurrentWorldDetails() in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/pages/ThriveopediaPatchMapPage.cs:line 69
   at Thriveopedia.set_CurrentGame(GameProperties value) in /home/hhyyrylainen/Projects/Thrive/src/thriveopedia/Thriveopedia.cs:line 135
   at PauseMenu.set_GameProperties(GameProperties value) in /home/hhyyrylainen/Projects/Thrive/src/general/PauseMenu.cs:line 111
   at StageBase.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/StageBase.cs:line 232
   at CreatureStageBase`2.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/general/base_stage/CreatureStageBase.cs:line 284
   at MicrobeStage.SetupStage() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/MicrobeStage.cs:line 780
   at MicrobeStage._Ready() in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/MicrobeStage.cs:line 160
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at StageBase.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/StageBase_ScriptMethods.generated.cs:line 208
   at CreatureStageBase`2.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/CreatureStageBase(Of TPlayer, TSimulation)_ScriptMethods.generated.cs:line 238
   at MicrobeStage.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /home/hhyyrylainen/Projects/Thrive/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/MicrobeStage_ScriptMethods.generated.cs:line 368
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret)
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
load finished, success: True message: Завантаження завершено elapsed: 00:00:02.8581285
```

**Comment by hhyyrylainen** [comment]
This error is probably the same root cause but for something that doesn't use NodePaths (probably):
```
ERROR: Scene instance is missing.
ERROR: at: (scene/resources/packed_scene.cpp:244)
ERROR: Failed to load Thriveopedia page Museum due to scene instantiate failure
```

**Comment by hhyyrylainen** [comment]
Another instance of that variant scene load failure:

```
Move to editor pressed
ERROR: Cannot get class ‘’.
ERROR: at: _instantiate_internal (core/object/class_db.cpp:549)
ERROR: WARNING: Node of type cannot be created. A placeholder will be created instead.
ERROR: at: instantiate (scene/resources/packed_scene.cpp:276)
ERROR: Cannot get class ‘’.
ERROR: at: _instantiate_internal (core/object/class_db.cpp:549)
```
